var StoreConstants = {
    SEARCH_FILTER_NEW: 'SEARCH_FILTER_NEW',
    SEARCH_FILTER_CLEAR: 'SEARCH_FILTER_CLEAR',
    SEARCH_DATA_NEW: 'SEARCH_DATA_NEW',
    SEARCH_DATA_ADD: 'SEARCH_DATA_ADD',
    SEARCH_SORT_BY: 'SEARCH_SORT_BY'
};
module.exports = StoreConstants;

